/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Comment: typeof import('./src/components/user/Comment.vue')['default']
    CommentAction: typeof import('./src/components/user/CommentAction.vue')['default']
    CommentFrame: typeof import('./src/components/user/CommentFrame.vue')['default']
    CommentInput: typeof import('./src/components/user/CommentInput.vue')['default']
    CommentLikeButton: typeof import('./src/components/user/CommentLikeButton.vue')['default']
    CommentList: typeof import('./src/components/user/CommentList.vue')['default']
    CommentReplyButton: typeof import('./src/components/user/CommentReplyButton.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    LoginCard: typeof import('./src/components/user/LoginCard.vue')['default']
    RegisterCard: typeof import('./src/components/user/RegisterCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
